# Generated by Django 5.2.4 on 2025-08-13 23:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aprovacao_disponibilidadeformadores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deslocamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('origem', models.CharField(blank=True, default='', max_length=255)),
                ('destino', models.CharField(blank=True, default='', max_length=255)),
                ('formadores', models.ManyToManyField(related_name='deslocamentos', to='core.formador')),
            ],
            options={
                'verbose_name': 'Deslocamento',
                'verbose_name_plural': 'Deslocamentos',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['data'], name='core_desloc_data_469969_idx')],
            },
        ),
    ]
