# Generated by Django 5.2.4 on 2025-08-19 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_clear_formador_area_atuacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'ordering': ['-data_hora'], 'permissions': [('view_relatorios', 'Can view consolidated reports')], 'verbose_name': 'Log de Auditoria', 'verbose_name_plural': 'Logs de Auditoria'},
        ),
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ['-data_solicitacao'], 'permissions': [('sync_calendar', 'Can sync with Google Calendar')]},
        ),
        migrations.RenameIndex(
            model_name='eventogooglecalendar',
            new_name='core_evento_provide_2683ec_idx',
            old_name='core_eventog_provide_b7f45d_idx',
        ),
        migrations.AlterField(
            model_name='formador',
            name='area_atuacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Área de Atuação'),
        ),
    ]
