# Generated by Django 5.2.4 on 2025-08-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_formador_area_atuacao_to_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ['-data_solicitacao'], 'permissions': [('sync_calendar', 'Can sync with Google Calendar'), ('view_own_solicitacoes', 'Can view own solicitações (Coordenador)')]},
        ),
    ]
