# Generated by Django 5.2.4 on 2025-08-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_papel_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprovacao',
            options={'ordering': ['-data_aprovacao']},
        ),
        migrations.AlterModelOptions(
            name='formador',
            options={'ordering': ['nome'], 'permissions': [('view_own_events', 'Can view own events (Formador)')], 'verbose_name': 'Formador', 'verbose_name_plural': 'Formadores'},
        ),
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'ordering': ['-data_hora'], 'permissions': [('view_relatorios', 'Can view consolidated reports')], 'verbose_name': 'Log de Auditoria', 'verbose_name_plural': 'Logs de Auditoria'},
        ),
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ['-data_solicitacao'], 'permissions': [('sync_calendar', 'Can sync with Google Calendar'), ('view_own_solicitacoes', 'Can view own solicitações (Coordenador)')]},
        ),
        migrations.AddField(
            model_name='projeto',
            name='vinculado_superintendencia',
            field=models.BooleanField(default=False, help_text='Projetos vinculados à superintendência requerem aprovação para eventos', verbose_name='Vinculado à Superintendência'),
        ),
    ]
