# Generated by Django 5.2.5 on 2025-08-31 23:57

import datetime
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_fix_tipo_evento_online_flags"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="solicitacao",
            index=models.Index(
                fields=["municipio", "data_inicio"],
                name="core_solici_municip_77644f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="solicitacao",
            index=models.Index(
                fields=["tipo_evento", "data_inicio"],
                name="core_solici_tipo_ev_7358b5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="solicitacao",
            constraint=models.UniqueConstraint(
                fields=("titulo_evento", "data_inicio"),
                name="unique_titulo_evento_data",
                violation_error_message="Já existe uma solicitação com o mesmo título nesta data.",
            ),
        ),
        migrations.AddConstraint(
            model_name="solicitacao",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_fim__gt", models.F("data_inicio"))),
                name="data_fim_after_inicio",
                violation_error_message="Data de fim deve ser posterior à data de início.",
            ),
        ),
        migrations.AddConstraint(
            model_name="solicitacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "data_fim__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("data_inicio"),
                            "+",
                            models.Value(datetime.timedelta(seconds=43200)),
                        ),
                    )
                ),
                name="max_duracao_12_horas",
                violation_error_message="Duração máxima de evento é 12 horas.",
            ),
        ),
    ]
