# Generated by Django 5.2.5 on 2025-09-01 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_add_solicitacao_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="CPF sem formatação (apenas números)",
                max_length=11,
                null=True,
                unique=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                help_text="Município de atuação do usuário",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.municipio",
                verbose_name="Município",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(
                blank=True,
                help_text="Telefone de contato",
                max_length=15,
                verbose_name="Telefone",
            ),
        ),
    ]
