# Generated by Django 5.2.4 on 2025-09-03 21:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_notification_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Superintendência, Vidas, Brincando e Aprendendo', max_length=100, unique=True, verbose_name='Nome do Setor')),
                ('sigla', models.CharField(help_text='Abreviação do setor (ex: SUPER, VIDAS, BRINC)', max_length=20, unique=True, verbose_name='Sigla')),
                ('vinculado_superintendencia', models.BooleanField(default=False, help_text='Marque apenas para o setor Superintendência. Projetos deste setor requerem aprovação.', verbose_name='É Setor Superintendência')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['setor__nome', 'nome'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AddField(
            model_name='projeto',
            name='codigo_produto',
            field=models.CharField(blank=True, help_text='ID/código do produto da planilha', max_length=50, verbose_name='Código do Produto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_produto',
            field=models.CharField(blank=True, help_text='Tipo/categoria do produto', max_length=100, verbose_name='Tipo do Produto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('gerente', 'Gerente'), ('coordenador', 'Coordenador'), ('apoio_coordenacao', 'Apoio de Coordenação'), ('formador', 'Formador'), ('controle', 'Controle'), ('admin', 'Administrador'), ('outros', 'Outros')], help_text='Cargo/função do usuário na organização', max_length=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='vinculado_superintendencia',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use setor.vinculado_superintendencia', verbose_name='Vinculado à Superintendência (DEPRECATED)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='setor',
            field=models.ForeignKey(blank=True, help_text='Setor organizacional responsável pelo projeto', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='setor',
            field=models.ForeignKey(blank=True, help_text='Setor organizacional do usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.setor', verbose_name='Setor'),
        ),
    ]
