# Generated by Django 5.2.4 on 2025-09-04 23:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_add_organizational_structure"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deslocamento",
            options={
                "ordering": ["-data", "tipo"],
                "verbose_name": "Deslocamento",
                "verbose_name_plural": "Deslocamentos",
            },
        ),
        migrations.AddField(
            model_name="deslocamento",
            name="pessoa_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deslocamentos_p1",
                to="core.formador",
                verbose_name="Pessoa 1",
            ),
        ),
        migrations.AddField(
            model_name="deslocamento",
            name="pessoa_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deslocamentos_p2",
                to="core.formador",
                verbose_name="Pessoa 2",
            ),
        ),
        migrations.AddField(
            model_name="deslocamento",
            name="pessoa_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deslocamentos_p3",
                to="core.formador",
                verbose_name="Pessoa 3",
            ),
        ),
        migrations.AddField(
            model_name="deslocamento",
            name="pessoa_4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deslocamentos_p4",
                to="core.formador",
                verbose_name="Pessoa 4",
            ),
        ),
        migrations.AddField(
            model_name="deslocamento",
            name="pessoa_5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deslocamentos_p5",
                to="core.formador",
                verbose_name="Pessoa 5",
            ),
        ),
        migrations.AddField(
            model_name="deslocamento",
            name="pessoa_6",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deslocamentos_p6",
                to="core.formador",
                verbose_name="Pessoa 6",
            ),
        ),
        migrations.AddField(
            model_name="deslocamento",
            name="tipo",
            field=models.CharField(
                choices=[("deslocamento", "Deslocamento"), ("retorno", "Retorno")],
                default="deslocamento",
                help_text="Tipo do deslocamento: ida ou volta",
                max_length=15,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="deslocamento",
            name="data",
            field=models.DateField(verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="deslocamento",
            name="destino",
            field=models.CharField(
                help_text="Local de chegada do deslocamento",
                max_length=255,
                verbose_name="Destino",
            ),
        ),
        migrations.AlterField(
            model_name="deslocamento",
            name="formadores",
            field=models.ManyToManyField(
                blank=True,
                help_text="DEPRECATED: Use pessoa_1 até pessoa_6",
                related_name="deslocamentos_old",
                to="core.formador",
            ),
        ),
        migrations.AlterField(
            model_name="deslocamento",
            name="origem",
            field=models.CharField(
                help_text="Local de partida do deslocamento",
                max_length=255,
                verbose_name="Origem",
            ),
        ),
        migrations.AddIndex(
            model_name="deslocamento",
            index=models.Index(
                fields=["data", "tipo"], name="core_desloc_data_b4ca44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deslocamento",
            index=models.Index(
                fields=["origem", "destino"], name="core_desloc_origem_d8c093_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deslocamento",
            constraint=models.CheckConstraint(
                condition=models.Q(("data__lte", datetime.date(2026, 9, 4))),
                name="data_not_too_far_future",
                violation_error_message="Data não pode ser mais de 1 ano no futuro.",
            ),
        ),
    ]
