# Generated by Django 5.2.4 on 2025-09-08 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_deslocamento_expansion"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deslocamento",
            name="data_not_too_far_future",
        ),
        migrations.AddConstraint(
            model_name="deslocamento",
            constraint=models.CheckConstraint(
                condition=models.Q(("data__lte", datetime.date(2026, 9, 8))),
                name="data_not_too_far_future",
                violation_error_message="Data não pode ser mais de 1 ano no futuro.",
            ),
        ),
    ]
