# Generated by Django 5.2.4 on 2025-09-12 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_deslocamento_data_not_too_far_future_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deslocamento",
            name="data_not_too_far_future",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="CPF sem formatação (apenas números) - usado como login no sistema",
                max_length=11,
                null=True,
                unique=True,
                verbose_name="CPF (Login)",
            ),
        ),
        migrations.AddConstraint(
            model_name="deslocamento",
            constraint=models.CheckConstraint(
                condition=models.Q(("data__lte", datetime.date(2026, 9, 12))),
                name="data_not_too_far_future",
                violation_error_message="Data não pode ser mais de 1 ano no futuro.",
            ),
        ),
    ]
