# Generated by Django 5.2.4 on 2025-09-19 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0023_remove_deslocamento_data_not_too_far_future_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area_atuacao',
            field=models.ForeignKey(
                blank=True,
                help_text='Grupo/área de atuação do usuário (ex: formador, coordenador)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='usuarios_area_atuacao',
                to='auth.group',
                verbose_name='Área de Atuação'
            ),
        ),
    ]
