# Generated by Django 5.2.4 on 2025-09-25 20:33

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_missing_fields'),
    ]

    operations = [
        # Create CursoPlataforma model
        migrations.CreateModel(
            name='CursoPlataforma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_curso', models.CharField(help_text='ID do curso na plataforma', max_length=50, unique=True)),
                ('categoria', models.CharField(help_text='Categoria do curso', max_length=200)),
                ('nome_breve', models.CharField(help_text='Nome breve do curso', max_length=200)),
                ('nome_limpo', models.CharField(blank=True, help_text='Nome processado pelo script de limpeza', max_length=200)),
                ('ano', models.IntegerField(default=2025, help_text='Ano do curso')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso da Plataforma',
                'verbose_name_plural': 'Cursos da Plataforma',
                'ordering': ['nome_breve'],
            },
        ),

        # Create ImportacaoCursosCSV model
        migrations.CreateModel(
            name='ImportacaoCursosCSV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('total_linhas', models.IntegerField(default=0)),
                ('cursos_importados', models.IntegerField(default=0)),
                ('cursos_atualizados', models.IntegerField(default=0)),
                ('vinculos_criados', models.IntegerField(default=0)),
                ('log_processamento', models.TextField(blank=True)),
                ('log_erros', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Importação CSV de Cursos',
                'verbose_name_plural': 'Importações CSV de Cursos',
                'ordering': ['-data_inicio'],
            },
        ),

        # Create ProjetoCursoLink model
        migrations.CreateModel(
            name='ProjetoCursoLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapeamento_manual', models.BooleanField(default=False, help_text='Se o mapeamento foi feito manualmente ou automaticamente')),
                ('data_vinculacao', models.DateTimeField(auto_now_add=True)),
                ('curso_plataforma', models.ForeignKey(help_text='Curso correspondente na plataforma', on_delete=django.db.models.deletion.CASCADE, to='core.cursoplataforma')),
                ('projeto', models.ForeignKey(help_text='Projeto do sistema', on_delete=django.db.models.deletion.CASCADE, related_name='cursos_vinculados', to='core.projeto')),
                ('usuario_vinculacao', models.ForeignKey(blank=True, help_text='Usuário que fez a vinculação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link Projeto-Curso',
                'verbose_name_plural': 'Links Projeto-Curso',
                'ordering': ['projeto__nome', 'curso_plataforma__nome_breve'],
            },
        ),

        # Add indexes for CursoPlataforma
        migrations.AddIndex(
            model_name='cursoplataforma',
            index=models.Index(fields=['id_curso'], name='core_cursop_id_curs_8cbbee_idx'),
        ),
        migrations.AddIndex(
            model_name='cursoplataforma',
            index=models.Index(fields=['categoria'], name='core_cursop_categor_c0ee04_idx'),
        ),
        migrations.AddIndex(
            model_name='cursoplataforma',
            index=models.Index(fields=['ano', 'ativo'], name='core_cursop_ano_91bd6f_idx'),
        ),

        # Add unique constraint for ProjetoCursoLink
        migrations.AddConstraint(
            model_name='projetocursolink',
            constraint=models.UniqueConstraint(fields=('projeto', 'curso_plataforma'), name='unique_projeto_curso_link'),
        ),
    ]
